# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GifMaker_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GifMaker

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GifMaker:
ifneq (,$(GifMaker_config))
	@echo "==== Building GifMaker ($(GifMaker_config)) ===="
	@${MAKE} --no-print-directory -C . -f GifMaker.make config=$(GifMaker_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f GifMaker.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GifMaker"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"